### ISSUE TITLE
NavBar problem

### ISSUE THREAD

**Issue by kandandiani** [NameLi/mind-ui-vue#1]
```
<m-navbar-group name="tab4" @click="onClick" @change="onChange">
	<m-navbar title="标签1" name="tab1" />
	<m-navbar title="标签2" name="tab2" />
	<m-navbar title="标签3" name="tab3" />
	<m-navbar title="标签4" name="tab4" />
	<m-navbar title="标签5" name="tab5" />
	<m-navbar title="标签6" name="tab6" />
	<m-navbar title="标签7" name="tab7" />
</m-navbar-group>
```
这个组件不能默认选中标签。
[
![image](https://user-images.githubusercontent.com/26077184/202524900-8bd56759-ef33-4b95-a1ea-8f630721ef3f.png)
](图片1)
如图 group 组件接受的是activeName, 而不是示例的name
在 navbar组件中，计算属性isActive() 并不能相等，navbar标签传的name会加上首尾空格。

**Comment by NameLi** [comment]
感谢您的反馈，今天修复了该组件说明文档中错误，并对组件增加了 v-model 支持；对其它组件与文档也进行了对照排查，所有更新请查看组件说明文档中的[更新日志](https://mind-ui-vue.ixook.com/docs/changelog/)
npm 包已发布修复后的新版。
